security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        main:
            anonymous: true
            logout:
                path: app_logout
                target: quack_index
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: '^/quack/new', roles: ROLE_USER }
         - { path: '^/quack/edit', roles: ROLE_USER }
         - { path: '^/quack/delete', roles: ROLE_USER }
         - { path: '^/user/quacksuser', roles: ROLE_USER }
         - { path: '^/user/delete', roles: ROLE_USER }
         - { path: '^/user/show', roles: ROLE_USER }
         - { path: '^/user/edit', roles: ROLE_USER }

         - { path: '^/register', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/', roles: IS_AUTHENTICATED_ANONYMOUSLY }

