swiftmailer:
    transport:        gmail
    username:         issou.jean.paul@gmail.com
    password:         issoujeanpaul
    host:             localhost
    port:             465
    encryption:       ssl
    auth-mode:        login
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false